# -*- coding: utf-8 -*-

"""
環境変数名定数
"""


# テーブル名
LEVEL_CAPS_TABLE_NAME: str = "LEVEL_CAPS_TABLE_NAME"
PLAYERS_TABLE_NAME: str = "PLAYERS_TABLE_NAME"

# インデックス名
PLAYERS_SEASON_ID_INDEX_NAME: str = "PLAYERS_SEASON_ID_INDEX_NAME"
