# -*- coding: utf-8 -*-

"""
環境変数名定数
"""

# AWS 標準環境変数
MY_AWS_REGION: str = "MY_AWS_REGION"

# テーブル名
LEVEL_CAPS_TABLE_NAME: str = "LEVEL_CAPS_TABLE_NAME"
PLAYERS_TABLE_NAME: str = "PLAYERS_TABLE_NAME"

# インデックス名
PLAYERS_SEASON_ID_INDEX_NAME: str = "PLAYERS_SEASON_ID_INDEX_NAME"

# 一時的に上昇させる書き込みキャパシティ
TEMPORARY_CAPACITY_UNITS: str = "TEMPORARY_CAPACITY_UNITS"
