# -*- coding: utf-8 -*-

"""
環境変数名定数
"""

# AWS 標準環境変数
MY_AWS_REGION: str = "MY_AWS_REGION"

# リソース名のプレフィックス
PREFIX: str = "PREFIX"

# ゆとシートにアクセスする感覚
GET_YTSHEET_INTERVAL_SECONDS: str = "GET_YTSHEET_INTERVAL_SECONDS"

# バケット名
MY_BUCKET_NAME: str = "MY_BUCKET_NAME"

# テーブル名
LEVEL_CAPS_TABLE_NAME: str = "LEVEL_CAPS_TABLE_NAME"
PLAYERS_TABLE_NAME: str = "PLAYERS_TABLE_NAME"

# インデックス名
PLAYERS_SEASON_ID_NAME_INDEX_NAME: str = "PLAYERS_SEASON_ID_NAME_INDEX_NAME"
